package com.rejunk.domain.enums;

public enum NotificationType {
    PAYMENT_CONFIRMED,
    PICKUP_SCHEDULED,
    ITEM_EVALUATED,
    LISTING_CREATED,
    ITEM_SOLD,
    PAYOUT_CREATED,
    ACCOUNT_SUSPENDED,

    COLLECTION_REQUEST_UPDATED,
    ITEM_ADDED,
    ITEM_PROCESSED

}